# Generated by Django 4.2 on 2024-07-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=100)),
                ('search_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
